##./bin/spark-submit --class cs.ucla.edu.bwaspark.BWAMEMSpark --master local[24] /home/hadoopmaster/standard_projects/bwa-spark-0.3.1/target/bwa-spark-0.3.1-assembly.jar

# run cloud-scale bwamem
# SAM output
#SPARK_DRIVER_MEMORY=24g /home/pengwei/spark-1.1.0/bin/spark-submit --executor-memory 36g --class cs.ucla.edu.bwaspark.BWAMEMSpark --total-executor-cores 48 --master spark://Jc11:7077 --driver-java-options "-XX:+PrintFlagsFinal" /home/ytchen/incubator/cloud-scale-bwamem-0.1.0/target/cloud-scale-bwamem-0.1.0-assembly.jar cs-bwamem -bfn 4 -bPSW 1 -sbatch 10 -bPSWJNI 1 -jniPath /home/ytchen/incubator/cloud-scale-bwamem-0.1.0/target/jniNative.so -oChoice 1 -oPath HCC1954_1_10M-14M_reads_1Mpart.sam 0 /home/hadoopmaster/genomics/ReferenceMetadata/human_g1k_v37.fasta hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/HCC1954_1_10M-14M_reads_1Mpart.fq 4

# ADAM output
#SPARK_DRIVER_MEMORY=24g /home/pengwei/spark-1.1.0/bin/spark-submit --executor-memory 36g --class cs.ucla.edu.bwaspark.BWAMEMSpark --total-executor-cores 48 --master spark://Jc11:7077 --driver-java-options "-XX:+PrintFlagsFinal" /home/ytchen/incubator/cloud-scale-bwamem-0.1.0/target/cloud-scale-bwamem-0.1.0-assembly.jar cs-bwamem -bfn 4 -bPSW 1 -sbatch 10 -bPSWJNI 1 -jniPath /home/ytchen/incubator/cloud-scale-bwamem-0.1.0/target/jniNative.so -oChoice 2 -oPath hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/output/HCC1954_1_10M-14M_1Mpart.adam 0 /home/hadoopmaster/genomics/ReferenceMetadata/human_g1k_v37.fasta hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/HCC1954_1_10M-14M_reads_1Mpart.fq 4

# store RDD
# single-end
#SPARK_DRIVER_MEMORY=40g /home/pengwei/spark-1.1.0/bin/spark-submit --executor-memory 20g --class cs.ucla.edu.bwaspark.BWAMEMSpark --total-executor-cores 48 --master spark://Jc11:7077 --driver-java-options "-XX:+PrintFlagsFinal" /home/ytchen/incubator/cloud-scale-bwamem-0.1.0/target/cloud-scale-bwamem-0.1.0-assembly.jar upload-fastq -bn 1000000 0 48 /home/ytchen/genomics/data/correctness_verification/HCC1954_1_10M-14M.fq hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/HCC1954_1_10M-14M_reads_1Mpart.fq
#SPARK_DRIVER_MEMORY=40g /home/pengwei/spark-1.1.0/bin/spark-submit --executor-memory 20g --class cs.ucla.edu.bwaspark.BWAMEMSpark --total-executor-cores 48 --master spark://Jc11:7077 --driver-java-options "-XX:+PrintFlagsFinal" /home/ytchen/incubator/cloud-scale-bwamem-0.1.0/target/cloud-scale-bwamem-0.1.0-assembly.jar upload-fastq -bn 7500000 0 48 /home/ytchen/genomics/data/correctness_verification/HCC1954_1_100M_reads.fq hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/HCC1954_1_100M_reads_7.5Mpart.fq
# pair-end
#SPARK_DRIVER_MEMORY=40g /home/pengwei/spark-1.1.0/bin/spark-submit --executor-memory 20g --class cs.ucla.edu.bwaspark.BWAMEMSpark --total-executor-cores 48 --master spark://Jc11:7077 --driver-java-options "-XX:+PrintFlagsFinal" /home/ytchen/incubator/cloud-scale-bwamem-0.1.0/target/cloud-scale-bwamem-0.1.0-assembly.jar upload-fastq -bn 1000000 1 48 /home/ytchen/genomics/data/correctness_verification/HCC1954_1_1-1M.fq /home/ytchen/genomics/data/correctness_verification/HCC1954_2_1-1M.fq hdfs://Jc11:9000/user/ytchen/data/correctness_verification/pair-end/HCC1954_1-1M.fq

# test command line
#SPARK_DRIVER_MEMORY=24g /home/pengwei/spark-1.1.0/bin/spark-submit --executor-memory 36g --class cs.ucla.edu.bwaspark.BWAMEMSpark --total-executor-cores 48 --master spark://Jc11:7077 --driver-java-options "-XX:+PrintFlagsFinal" /home/ytchen/incubator/cloud-scale-bwamem-0.1.0/target/cloud-scale-bwamem-0.1.0-assembly.jar help

# Berkeley ADAM
#/home/ytchen/incubator/adam-adam-parent-0.14.0/bin/adam-submit --master spark://Jc11:7077 --driver-memory 20g --executor-memory 36g transform -coalesce 192 hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/output/HCC1954_1_10M-14M_1Mpart_comp.sam hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/output/HCC1954_1_10M-14M_1Mpart_comp.adam
#/home/ytchen/incubator/adam-adam-parent-0.14.0/bin/adam-submit --master spark://Jc11:7077 --driver-memory 20g --executor-memory 36g transform -sort_reads hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/output/HCC1954_1_10M-14M_1Mpart.adam/0 hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/output/HCC1954_1_10M-14M_1Mpart_sorted.adam
/home/ytchen/incubator/adam-adam-parent-0.14.0/bin/adam-submit --master spark://Jc11:7077 --driver-memory 20g --executor-memory 36g compare -parquet_compression_codec GZIP -output compare.adam hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/output/HCC1954_1_10M-14M_1Mpart.adam/0 hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/output/HCC1954_1_10M-14M_1Mpart_comp.adam
#/home/ytchen/incubator/adam-adam-parent-0.14.0/bin/adam-submit --master spark://Jc11:7077 --driver-memory 20g --executor-memory 36g print hdfs://Jc11:9000/user/ytchen/data/correctness_verification/single-end/output/HCC1954_1_10M-14M_1Mpart.adam/0 -o HCC1954_1_10M-14M_1Mpart.adam
