#include <stdio.h>
#include <jni.h>
#include <jni_mate_sw.h> // generated by javah via maven-native-plugin

JNIEXPORT void JNICALL Java_cs_ucla_edu_bwaspark_jni_HelloWorld_helloWorld(JNIEnv * env, jobject obj)
{
   printf("Hello World from C\n");
}

